parameters:
  - name: environment
    type: string
    values:
      - test

name: toolbox-deploy-$(Rev:r)

trigger:
- none

resources:
- repo: self

variables:
  agent: <AGENT_NAME>
  containerRegistry: <ACR_NAME>
  imageRepository: toolbox
  imageTag: '$(Build.BuildNumber)'
  kubernetesServiceConnection: <AKS_SERVICE_CONNECTION_NAME>
  namespace: <NAMESPACE_NAME>

pool: $(agent)

stages:
- stage: Deploy
  displayName: Deploy stage
  jobs:
  - deployment: Deploy
    displayName: Deploy
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Deploy to Kubernetes cluster
            inputs:
              kubernetesServiceConnection: $(kubernetesServiceConnection)
              #if you remove namespace it will use the default namespace
              namespace: $(namespace)
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/toolbox.yml
              containers: |
                $(containerRegistry)/$(imageRepository):latest
