apiVersion: v1
kind: Pod
metadata:
  name: secret-app
  namespace: $namespace
  labels:
    name: secret-pod
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  serviceAccountName: $serviceAccountName
  containers:
    - image: docker.io/aranaescobedo/workload-id-app-aks:1.0
      name: secret-container
      env:
        - name: KEYVAULT_NAME
          value: $kvName
        - name: SECRET_NAME
          value: $mySecretName
